### ISSUE TITLE
mediaserver denials in AOSP N

### ISSUE THREAD

**Issue by tstein** [sonyxperiadev/device-sony-sepolicy#175]
I'm currently building `7.1.1_r25` for `e5823` with a fresh tree and extra attention to following the instructions (thanks, jerpelea :) ). Opening the camera hangs on a black screen with the following denial in logcat:
`avc:  denied  { add } for service=media.camera pid=529 uid=1013 scontext=u:r:mediaserver:s0 tcontext=u:object_r:cameraserver_service:s0 tclass=service_manager permissive=
0`

With that permitted, there's a second denial:
`avc:  denied  { find } for service=media.camera.proxy pid=532 uid=1013 scontext=u:r:mediaserver:s0 tcontext=u:object_r:cameraproxy_service:s0 tclass=service_manager permissive=0`

`audit2allow` generated these two rules, which I added to `mediaserver.te`:
```
allow mediaserver cameraserver_service:service_manager add;
allow mediaserver cameraproxy_service:service_manager find;
```
Subsequent builds have no camera-related denials, and the camera works. I'm submitting this as an issue rather than a pull request because I'm not sure what the root cause is or if this is the right way to fix it. Please let me know if you need any additional info.

**Comment by jerpelea** [comment]
please pr

**Comment by tstein** [comment]
Done - see you at https://github.com/sonyxperiadev/device-sony-sepolicy/pull/176 . Sorry, just very unsure of my fix. :)
