### ISSUE TITLE
zygote services

### ISSUE THREAD

**Issue by alviteri** [sonyxperiadev/device-sony-sepolicy#512]
04-12 01:32:23.694   697   697 I Binder:697_1: type=1400 audit(0.0:578): avc: denied { use } for path="anon_inode:dmabuf" dev="anon_inodefs" ino=13989 scontext=u:r:zygote:s0 tcontext=u:r:hal_graphics_allocator_default:s0 tclass=fd permissive=1
04-12 01:32:23.714  2098  2098 I RenderThread: type=1400 audit(0.0:579): avc: denied { ioctl } for path="/dev/kgsl-3d0" dev="tmpfs" ino=16596 ioctlcmd=0x945 scontext=u:r:zygote:s0 tcontext=u:object_r:gpu_device:s0 tclass=chr_file permissive=1
04-12 01:32:24.764  2098  2098 I ndroid.settings: type=1400 audit(0.0:627): avc: denied { read } for scontext=u:r:zygote:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1
04-12 01:32:25.014  2067  2067 I Binder:2067_9: type=1400 audit(0.0:631): avc: denied { use } for path="/dev/ashmem" dev="tmpfs" ino=17563 ioctlcmd=0x7704 scontext=u:r:zygote:s0 tcontext=u:r:system_server:s0 tclass=fd permissive=1
04-12 01:32:25.824   675   675 I HwBinder:675_1: type=1400 audit(0.0:645): avc: denied { call } for scontext=u:r:hal_bluetooth_default:s0 tcontext=u:r:zygote:s0 tclass=binder permissive=1

@ix5 @jerpelea

**Comment by ix5** [comment]
Sounds like `r35` stuff that El Goog forgot the sepolicy for

**Comment by Haxk20** [comment]
@jerpelea Please close this too.
